- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# setup load balancer tier
- name: setup load balancer tier
  hosts: frontends
  become: yes
  pre_tasks: 
  - name: Include common-vars
    include_vars: vars/common-vars.yml
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, backend_port: "{{apps_port}}", listen_port: "{{frontend_port}}", tags: [lbs, haproxy]}

# setup application servers tier
- name: setup application servers tier
  hosts: apps
  become: yes
  gather_facts: false
  pre_tasks: 
  - name: Include common-vars
    include_vars: vars/common-vars.yml
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tomcat_listen_port: "{{apps_port}}", tags: [apps, tomcat]}

# setup database tier
- name: setup database tier
  become: yes
  hosts: appdbs
  pre_tasks: 
  - name: Include common-vars
    include_vars: vars/common-vars.yml
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}
