- hosts: frontends
  gather_facts: false
  pre_tasks: 
  - name: Include common-vars
    include_vars: vars/common-vars.yml
  tasks:
  - name: HTTP Request Frontend
    uri:
      url: "{{ frontend_protocol }}://localhost"
      return_content: yes
      status_code: 200
    register: webpage
    failed_when: apps_validation_content not in webpage.content

  - debug: var=webpage.content
