---
# vars file for osp-servers role

osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
    net_interface: 
      - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    net_interface: 
      - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    net_interface: 
      - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    meta:
      - { group: apps, deployment_name: QA}
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: db
    net_interface: 
      - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    meta:
      - { group: appdbs, deployment_name: QA}
