---
- name: Install and config HAProxy
  block:

  - name: Install HAProxy
    yum:
      name: "{{ payload }}"
      state: latest
    notify: restart haproxy

  - name: Start and enable HAProxy
    service: 
      name: "{{ payload }}"
      state: started
      enabled: yes
  tags:
    - "haproxy:install"

- name: Configure HAProxy with template
  block:
    - name: Prepare configuration
      template: 
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy
  tags:
    - "haproxy:configure"
