---
# tasks file for osp-servers roles

- name: QA Instances provisiong

  block:
    - name: Provision OSP Instances
      os_server:
        cloud: openstack
        name: "{{item.value.name}}"
        state: "{{item.value.state}}"
        image: "{{item.value.image}}"
        key_name: "{{item.value.key_name}}"
        flavor: "{{item.value.flavor}}"
        nics: "{{item.value.net_interface}}"
        meta: "{{item.value.meta[0]}}"
        security_groups: ["{{item.value.security_group}}"]
        user_data: "{{global_userdata}}"
      loop: "{{osp_servers | dict2items}}"
    
    - name: Allocate FIPs
      os_floating_ip:
        cloud: openstack
        state: "{{item.value.state}}"
        server: "{{item.value.name}}"
        network: "{{item.value.ext_network}}"
        nat_destination: "{{item.value.int_network}}"
      loop: "{{osp_servers | dict2items}}"

  rescue: 
    - name: Failure Message
      debug:
        msg: "OSP instances failed. Cleaning up Env"
        
    - name: Clean up failed instances
      os_server: 
        cloud: openstack
        name: "{{item.value.name}}"
        state: absent
      loop: "{{osp_servers | dict2items}}"

    - name: Fail after clean up
      fail:
      when: yes
