---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update package repository (Debian)
      apt: update_cache=true
      when: ansible_os_family == "Debian"
      changed_when: false  # to pass idemotence test
    - name: update package repository (Red Hat)
      yum: update_cache=true
      when: ansible_os_family == "RedHat"
      changed_when: false  # to pass idemotence test
    - name: install netstat (Debian/Red Hat)
      package: name=net-tools state=present
      when: >
        ansible_os_family == "Debian" or
        ansible_os_family == "RedHat"
    # basic setup / fixes
    - name: basic server setup (includes locale)
      include_role:
        name: bihealth.basic_server
  roles:
    - role: ansible-role-postgres-server
